Second iteration
DSugakov/go-sprint-four pull request #1
Opened 2023-12-10 16:10 UTC by DSugakov

MR в свой main

2023-12-11 13:05 UTC, just-musha requested changes
Привет! Спасибо за работу. Предлагаю поправить вызов функции средней скорости для swimming, и проверить формулу там где комментарий. В остальном 
 - не критично, все супер. Жду правки, и готова принять работу.

2023-12-11 13:05 UTC, just-musha commented on ftracker.go
> +		speed := meanSpeed(action, duration)                                       // вызовите здесь необходимую функцию
У плавания своя формула расчета средней скорости, давай вызовем её

2023-12-11 13:05 UTC, just-musha commented on ftracker.go
> +	// (СредняяСкоростьВКм/ч + 1.1) * 2 * ВесСпортсменаВКг * ВремяТренеровкиВЧасах
Вспомогательные комментарии лучше подчищать, чтобы не засорять код

2023-12-11 18:16 UTC, DSugakov commented on ftracker.go
> +	return ((walkingCaloriesWeightMultiplier*weight + math.Pow(meanSpeed(action, duration), 2)/height) / (height / cmInM) * walkingSpeedHeightMultiplier * weight) * duration * minInH
исправлено

2023-12-11 18:16 UTC, DSugakov commented on ftracker.go
> +		speed := meanSpeed(action, duration)                                       // вызовите здесь необходимую функцию
исправлено

2023-12-11 18:16 UTC, DSugakov commented on ftracker.go
> +	// (СредняяСкоростьВКм/ч + 1.1) * 2 * ВесСпортсменаВКг * ВремяТренеровкиВЧасах
исправлено

2023-12-12 06:18 UTC, just-musha requested changes
Спасибо! В формуле калорий для walking можешь ещё раз проверить, там что-то со скобками. В остальном все хорошо.

2023-12-12 06:18 UTC, just-musha commented on .gitignore
> +/ftracker_test.go
А этот файл нужнен, изменения в тестах мы бы хотели отслеживать в реальном проекте. Можно убрать из gitignore

2023-12-12 06:18 UTC, just-musha commented on ftracker.go
> +	// ((0.035 * ВесСпортсменаВКг + (СредняяСкоростьВМетрахВСекунду**2 / РостВМетрах) * 0.029 * ВесСпортсменаВКг) * ВремяТренировкиВЧасах * minInH)
Тоже комент который можно подчистить

2023-12-12 06:18 UTC, just-musha commented on ftracker.go
> +	return ((walkingCaloriesWeightMultiplier*weight + math.Pow(meanSpeed(action, duration)*kmhInMsec, 2)/(height/cmInM)) * walkingSpeedHeightMultiplier * weight) * duration * minInH
Что-то здесь со скобками, проверь пожалуйста ещё раз

2023-12-12 07:07 UTC, just-musha approved these changes
Принимаю, но проверку на 0 стоит вернуть, пержде чем делить она нужна

2023-12-12 07:07 UTC, just-musha commented on ftracker.go
> -	if duration == 0 {
Проверка все-таки нужна, давай оставим

2023-12-12 16:03 UTC, merged